export const ErrorMessages = {
  INVALID_PARAM: (param: string, value: string) =>
    `O ${param} ${value} é invalido`,
  USER_DOES_NOT_EXIST: 'Usuário não existe!',
  INVALID_CREDENTIAL: 'E-mail e/ou senha são inválidos!',
  USER_ALREADY_EXIST: 'Usuário já registrado!',
  INVALID_EMAIL: 'Email invalido',
  INVALID_CREDENTIALS: 'Credenciais invalidas',
  INVALID_PIN: 'PIN invalido',
  INVALID_NAME: 'Nome invalido',
  INVALID_CURRENCY: 'Moeda invalida',
  INVALID_PASSWORD:
    'Senha não pode ser menor que 8 caracteres ou maior que 255',
  INVALID_CNPJ: (CNPJ: string) => `o CNPJ "${CNPJ}" é invalido.`,
  INVALID_ENUM_TRANSACTION_STATUS: 'Status de transação invalido',
  INVALID_ENUM_TRANSACTION_TYPE: 'Tipo de transação invalida',
  INVALID_ENUM_DOCUMENT_STATUS: 'Status de documento invalido',
  BALANCE_NOT_FOUND: 'Error com o saldo das carteiras',
  INSUFFICIENT_BALANCE: 'Saldo insuficiente para completar a transação',
  CANNOT_TRANSFER_TO_SOURCE_WALLET:
    'Não é possível transferir para a mesma carteira',
  WALLET_DOES_NOT_EXISTS: 'Carteira não existe',
  CARD_DOES_NOT_EXISTS: 'Cartão não existe',
  CARD_ALREADY_EXISTS: 'Cartão já registrado',
  PARTNER_ALREADY_EXISTS: 'Parceiro já registrado',
  PARTNER_DOES_NOT_EXISTS: 'Parceiro não existe',
  INVALID_PARTNER: 'Parceiro está bloqueado ou não existe',
  MEMBER_ALREADY_EXISTS: 'Membro já registrado',
  INVALID_TOKEN_ERROR: 'token invalido',
};
