version: '3.9'
services:
  # nix-api:
  #   container_name: nix-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  postgres:
    image: postgres:latest
    container_name: nix_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nix_database
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - qrcard-api-net

networks:
  qrcard-api-net:
    driver: bridge
volumes:
  postgres:
    name: nix_database