export const TOKENS = {
  USERS_REPOSITORY: 'USERS.repository',
  MANGAS_REPOSITORY: 'USERS.repository',
  CHAPTERS_REPOSITORY: 'CHAPTERS.repository',
  CHAPTERS_PAGES_REPOSITORY: 'CHAPTERS_PAGES.repository',
  SCANS_REPOSITORY: 'SCANS.repository',
  SCANS_MANGAS_REPOSITORY: 'SCANS_MANGAS.repository',
  STORAGE_PROVIDER: 'STORAGE.provider',
};
